version: "3"
services:
    nginx-php-v4:
        hostname: elearning-v4
        container_name: elearning-v4
        image: dootvmedia/ubuntu:nginx-php7.1
        ports: 
            - 84:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www_v4:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.1/fpm
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
        cap_add:
            - SYS_PTRACE
        restart: always

