version: "3"
services:       
    db-slave:
        hostname: db-slave
        container_name: db-slave
        image: mysql
        ports:
            - 4406:3306
        volumes:
            - ./config/database_cfg/slave.cnf:/etc/mysql/conf.d/slave.cnf
            - ./data/db-slave:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=dootvazws3e
        restart: always
     
    nginx-php2:
        hostname: web2
        container_name: web2
        image: dootvmedia/nginx-php:php7
        ports: 
            - 8080:80
            - 443:443
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php/php.ini:/etc/php5/fpm/php.ini
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        restart: always
