version: "2"
services:
    haproxy:
        image: haproxy:1.6.9
        ports:
            - 80:80
            - 1936:1936
        volumes:
            - /data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        environment:
            - TZ=Asia/Bangkok
        restart: always
        
    nginx-php-1:
        image: dootvmedia/nginx-php:master
        ports: 
            - 8001:80        
        volumes:
            - /data/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - /data/nginx/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /data/nginx/etc/php/php.ini:/etc/php5/fpm/php.ini
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        restart: always
        
    nginx-php-2:
        image: dootvmedia/nginx-php:master
        ports: 
            - 8002:80        
        volumes:
            - /data/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - /data/nginx/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /data/nginx/etc/php/php.ini:/etc/php5/fpm/php.ini
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        restart: always

    mysql:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - /data/mysql:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=password
        restart: always

