version: "3"
services:
    db-master:
        hostname: db-master
        container_name: db-master
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./config/database_cfg/master.cnf:/etc/mysql/conf.d/master.cnf
            - /data/db-master:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=dootvazws3e
        restart: always
       
    nginx-php1:
        hostname: web1
        container_name: web1
        image: dootvmedia/nginx-php:php7
#        ports: 
#            - 80:80
#            - 443:443
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.0/fpm
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        privileged: true
        network_mode: "host"
        restart: always

    haproxy:
        hostname: haproxy
        image: haproxy
        container_name: haproxy
        ports:
            - 8443:443
            - 880:80
            - 1936:1936
        links:
            - nginx-php1
        volumes:
            - ./config/haproxy:/usr/local/etc/haproxy:ro
        environment:
            - TZ=Asia/Bangkok
        restart: always
