version: "3"
services:
    nginx-php7.0:
        hostname: nginx-php7.0
        container_name: test_nginx-php7.0
        image: dootvmedia/ubuntu:nginx-php7.0
        ports:
            - 8001:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.0/fpm
        environment:
            - TZ=Asia/Bangkok
        restart: always

    nginx-php7.1:
        hostname: nginx-php7.1
        container_name: test_nginx-php7.1
        image: dootvmedia/ubuntu:nginx-php7.1
        ports:
            - 8002:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.1/fpm
        environment:
            - TZ=Asia/Bangkok
        restart: always

    nginx-php7.2:
        hostname: nginx-php7.2
        container_name: test_nginx-php7.2
        image: dootvmedia/ubuntu:nginx-php7.2
        ports:
            - 8003:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.2/fpm
        environment:
            - TZ=Asia/Bangkok
        restart: always