version: "3"
services:
    db-master:
        hostname: db-master
        container_name: db-master
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./config/database_cfg/master.cnf:/etc/mysql/conf.d/master.cnf
            - /data/db-master:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=dootvazws3e
        restart: always

    nginx-php:
        hostname: elearning-v3
        container_name: elearning-v3
        image: dootvmedia/ubuntu:nginx-php7.1
        ports: 
            - 8080:80
            - 8444:443
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/www:/usr/share/nginx/html
            - /raid:/raid
            - ./config/nginx-php/etc/php-fpm:/etc/php/7.1/fpm
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
        cap_add:
            - SYS_PTRACE
        restart: always

    haproxy:
        hostname: haproxy
        image: haproxy
        container_name: haproxy
        ports:
            - 443:443
            - 80:80
            - 1936:1936
        links:
            - nginx-php
        volumes:
            - ./config/haproxy:/usr/local/etc/haproxy:ro
        environment:
            - TZ=Asia/Bangkok
        restart: always

