version: "3"
services:
    db-master:
        hostname: db-master
        container_name: db-master
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./config/database_cfg/master.cnf:/etc/mysql/conf.d/master.cnf
            - ./data/db-master:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=dootvazws3e
        restart: always
        depends_on:
            - db-slave
        
    db-slave:
        hostname: db-slave
        container_name: db-slave
        image: mysql
        ports:
            - 4406:3306
        volumes:
            - ./config/database_cfg/slave.cnf:/etc/mysql/conf.d/slave.cnf
            - ./data/db-slave:/var/lib/mysql
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=dootvazws3e
        restart: always
     
        
    nginx-php1:
        hostname: web1
        container_name: web1
        image: dootvmedia/nginx-php:php7
        ports: 
            - 81:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - ./data/www:/usr/share/nginx/html
            -  /raid:/raid
            - ./config/nginx-php/etc/php/php.ini:/etc/php5/fpm/php.ini
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        restart: always

    nginx-php2:
        hostname: web2
        container_name: web2
        image: dootvmedia/nginx-php:php7
        ports: 
            - 82:80
        volumes:
            - ./config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - ./data/www:/usr/share/nginx/html
            -  /raid:/raid
            - ./config/nginx-php/etc/php/php.ini:/etc/php5/fpm/php.ini
            - ./config/nginx-php/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
            - TEMPLATE_NGINX_HTML=0
        restart: always
        
    haproxy-certbot:
        hostname: haproxy-certbot
        container_name: haproxy-certbot
        image: nmarus/haproxy-certbot
        ports:
            - 80:80
            - 443:443
            - 1936:1936
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config/haproxy-certbot/config:/config
            - ./config/haproxy-certbot/letsencrypt:/etc/letsencrypt
            - ./config/haproxy-certbot/certs.d:/usr/local/etc/haproxy/certs.d
        environment:
            - TZ=Asia/Bangkok
        restart: always
